networks:
  amap.net:
    driver: bridge

services:

  php:
    image: canals/php:8.3
    container_name: amap_php
    ports:
      - '1000:80'
    networks:
      - amap.net
    env_file: ./secret.env
    restart: unless-stopped
    volumes:
      - ./api:/var/www/html
    working_dir: /var/www/html
    depends_on:
      amap.db:
        condition: service_healthy

  adminer:
    image: 'adminer'
    container_name: amap_adminer
    ports:
      - '1001:8080'
    networks:
      - amap.net
    command: php -S 0.0.0.0:8080 -t /var/www/html
    restart: unless-stopped
    depends_on:
      amap.db:
        condition: service_healthy

  amap.db:
    image: postgres:alpine
    container_name: amap_pgsql
    ports:
      - "1002:5432"
    volumes:
      - ./sql:/var/sql
    env_file: ./db.env
    networks:
      - amap.net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      retries: 5
      timeout: 10s

  angular:
    image: node:20
    container_name: amap_angular
    working_dir: /app
    volumes:
      - ./Front:/app
    ports:
      - "1005:4200"
    command: sh -c "npm install && npx ng serve --host 0.0.0.0 --port 4200 --public-host=http://localhost:1003"
    networks:
      - amap.net
    restart: unless-stopped
