networks:
  amap.net:
    driver: bridge

services:

  php:
    image: canals/php:8.3
    container_name: amap_php
    ports:
      - '1000:80'
    networks:
      - amap.net
    restart: unless-stopped
    volumes:
      - ./api:/var/www/html
    depends_on:
      pgsql:
        condition: service_healthy

  adminer:
    image: 'adminer'
    container_name: amap_adminer
    ports:
      - '1001:8080'
    networks:
      - amap.net
    command: php -S 0.0.0.0:8080 -t /var/www/html
    restart: unless-stopped
    depends_on:
      pgsql:
        condition: service_healthy

  pgsql:
    image: postgres:alpine
    container_name: amap_pgsql
    ports:
      - "1002:5432"
    volumes:
      - ./sql:/var/sql
    env_file: ./db.env
    networks:
      - amap.net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      retries: 5
      timeout: 10s



